# Generated by Django 6.0.2 on 2026-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_accepted_at_incident_arrived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='caller_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
