# Generated by Django 6.0.2 on 2026-02-15 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_caller_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='address_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim_first_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim_last_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='incident',
            name='caller_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('ARRIVED', 'Arrived'), ('DONE', 'Done'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(default='Vizov', max_length=120),
        ),
    ]
