# Generated by Django 6.0.2 on 2026-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_address_text_incident_victim_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Murojaat', 'verbose_name_plural': 'Murojaatlar'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('ASSIGNED', 'Biriktirildi'), ('ACCEPTED', 'Qabul qilindi'), ('ARRIVED', 'Yetib keldi'), ('DONE', 'Bajarildi'), ('CLOSED', 'Yopildi'), ('CANCELED', 'Bekor qilindi')], default='NEW', max_length=20),
        ),
    ]
